version: '3.8'
services:
  node:
    container_name: app
    build: .  
    depends_on:
      - postgres      
    networks: 
      - backend
    restart: always
    ports: 
      - "${PORT}:${PORT}"      
    volumes: 
      - .:/usr/app    
      - /usr/app/node_modules  
  postgres:
    container_name: postgres
    image: postgres:13.3
    networks: 
      - backend
    restart: always
    ports: 
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"    
    environment: 
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PG_DATA: /var/lib/postgresql/data        
    volumes: 
      - pgdata:/var/lib/postgresql/data

networks: 
  backend:
    driver: bridge
volumes:
  pgdata:
