version: '3'
services:
  node:
    build: .
    container_name: app
    networks: 
      - backend
    restart: on-failure
    ports: 
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    environment: 
      - PORT=4000
    volumes: 
      - .:/usr/app
  postgres:
    build: ./src/database
    networks: 
      - backend
    restart: on-failure
    ports: 
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment: 
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes: 
      - pgdata:/var/lib/postgresql/data

networks: 
  backend:
    driver: bridge
volumes:
  pgdata:
